title: John Samstad # your name (or website title) here
logo: "/images/logo.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Recovering public accountant who digs data 
  <br><br>
  <a href="https://www.linkedin.com/in/johnsamstad/">View My LinkedIn Profile</a> 
